name: Tests

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ./cover.out
          flags: go-tests
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: otterscale/tenant-operator
